
function T = make_table(first_col_title, name, run_time, n_iter, p_res, p_res_rel, p_res_L2, ...
                    d_res, d_res_rel, d_res_L2, objval, show_all,...
                    i_time, s_time, m_time)

  if(nargin <= 12)
    show_time = false;
  else
    show_time = true;
  end
  if(show_time)
    if(show_all==2)
      T = table(name, run_time, n_iter,p_res_rel, d_res_rel, ...
            i_time, s_time, m_time, objval);  
      T.Properties.VariableNames={first_col_title,'run_time','n_iter',...
               'res_prim_rel', ...
               'res_dual_rel', ...
               'init_time', 'solver_time', 'model_time', 'objval'};

    elseif(show_all==1)
      T = table(name, run_time, n_iter, p_res, p_res_rel, p_res_L2, d_res, d_res_rel, d_res_L2, objval,...
            i_time, s_time, m_time);  
      T.Properties.VariableNames={first_col_title,'run_time','n_iter',...
               'res_prim_abs','res_prim_rel','res_prim_L2', ...
               'res_dual_abs', 'res_dual_rel', 'res_dual_L2', 'objval',...
               'init_time', 'solver_time', 'model_time'};
   else   
      T = table(name, run_time, n_iter,p_res_rel, d_res_rel, ...
            i_time, s_time, m_time);  
      T.Properties.VariableNames={first_col_title,'run_time','n_iter',...
               'res_prim_rel', ...
               'res_dual_rel', ...
               'init_time', 'solver_time', 'model_time'};
    end
  else
    if(show_all==2)         
      T = table(name, run_time, n_iter,p_res_rel, d_res_rel, objval);  
      T.Properties.VariableNames={first_col_title,'run_time','n_iter',...
               'res_prim_rel', ...
               'res_dual_rel', 'objval'};
    elseif(show_all==1)
      T = table(name, run_time, n_iter, p_res, p_res_rel, p_res_L2, d_res, d_res_rel, d_res_L2, objval);  
      T.Properties.VariableNames={first_col_title,'run_time','n_iter',...
               'res_prim_abs','res_prim_rel','res_prim_L2',...
               'res_dual_abs', 'res_dual_rel', 'res_dual_L2', 'objval'};
    else     
      T = table(name, run_time, n_iter,p_res_rel, d_res_rel);  
      T.Properties.VariableNames={first_col_title,'run_time','n_iter',...
               'res_prim_rel', ...
               'res_dual_rel'};
    end
  end
end